name: tests
options:
    bundleIdPrefix: inl.tests
    xcodeVersion: "16.2"
    deploymentTarget:
        iOS: "17.5"
configs:
    Debug: debug
    Release: release
    Staging Debug: debug
    Staging Release: release
schemes:
    tests Staging:
        build:
            targets:
                tests: all
        run:
            config: Staging Debug
        test:
            config: Staging Debug
            gatherCoverageData: true
            coverageTargets:
                - tests
            targets:
                - testsTests
        profile:
            config: Staging Release
        analyze:
            config: Staging Debug
        archive:
            config: Staging Release

settings:
GENERATE_INFOPLIST_FILE: NO
targets:
    tests:
        platform: iOS
        type: application
        deploymentTarget: "17.5"
        sources: ["tests"]
        settings:
            base:
                INFOPLIST_FILE: "tests/Info.plist"
        scheme:
            testTargets:
             - testsTests
        postBuildScripts:
    testsTests:
        platform: iOS
        type: bundle.unit-test
        deploymentTarget: "18.2"
        sources: ["Tests"]
        dependencies:
            - target: tests
        settings:
            base:
                INFOPLIST_FILE: "tests/Info.plist"
