options:
    bundleIdPrefix: com.mariamayorova
    xcodeVersion: "16.2»
    deploymentTarget:
        iOS: "17.2"
configs:
    Debug: debug
    Release: release
    Staging Debug: debug
    Staging Release: release
configFiles:
    Debug: SiriusProject/configs/Dev.xcconfig
    Release: SiriusProject/configs/Dev.xcconfig
    Staging Debug: SiriusProject/configs/Staging.xcconfig
    Staging Release: SiriusProject/configs/Staging.xcconfig
schemes:
    SiriusProject Staging:
        build:
            targets:
                SiriusProject: all
        run:
            config: Staging Debug
        test:
            config: Staging Debug
            gatherCoverageData: true
            coverageTargets:
                - SiriusProject
            targets:
                - SiriusProject
        profile:
            config: Staging Release
        analyze:
            config: Staging Debug
        archive:
            config: Staging Release

settings:
GENERATE_INFOPLIST_FILE: NO
targets:
    SiriusProject:
        platform: iOS
        type: application
        deploymentTarget: "18.2"
        sources: ["SiriusProject"]
        settings:
            base:
                INFOPLIST_FILE: "SiriusProject/Info.plist"
        scheme:
            testTargets:
             - SiriusProjectTests
    SiriusProjectTests:
        platform: iOS
        type: bundle.unit-test
        deploymentTarget: "18.2"
        sources: ["SiriusProjectTests"]
        dependencies:
            - target: SiriusProject
        settings:
            base:
                INFOPLIST_FILE: "SiriusProject/Info.plist"
