name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install --repo-update
        working-directory: ios_project_directory  # Укажите директорию проекта

      - name: Build project
        run: |
          xcodebuild clean build \
          -workspace MyApp.xcworkspace \
          -scheme MyApp \
          -sdk iphoneos \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

      - name: Run tests
        run: |
          xcodebuild test \
          -workspace MyApp.xcworkspace \
          -scheme MyApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

  deploy:
    name: Deploy to TestFlight
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install fastlane
          bundle install
        working-directory: ios_project_directory

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          fastlane beta
