name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test iOS App
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build project
        run: |
          xcodebuild -project tests.xcodeproj \
          -sdk iphoneos \
          -scheme "tests" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          clean build
