name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app


      - name: Build project
        run: |
          xcodebuild clean build \
          -workspace tests.xcodeproj \
          -scheme tests \
          -sdk iphoneos \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
